## Joining excel files

In [2]:
import pandas as pd

In [6]:
import unicodecsv as csv
# df = pd.read_csv('C:/Users/Gajraj/Documents/Brand-AE.csv', encoding = 'ascii')
excel_workbook = 'C:\\Users\\Gajraj Singh\\Downloads\\G-Device-Report-Mumzworld-Feb-1-2021-Feb-13-2021.xlsx'
df1 = pd.read_excel(excel_workbook, sheet_name = 'Raw Data Report')
# df1 = pd.read_excel(excel_workbook, sheet_name = 'Daily-Geo')
# df2 = pd.read_excel(excel_workbook, sheet_name = 'Daily-Age-Gender')
excel_workbook = 'C:\\Users\\Gajraj Singh\\Downloads\\G-Device-Report-Mumzworld-Jan-1-2021-Jan-31-2021.xlsx'
df2 = pd.read_excel(excel_workbook, sheet_name = 'Raw Data Report')

excel_workbook = 'C:\\Users\\Gajraj Singh\\Downloads\\G-Device-Report-Mumzworld-Dec-1-2020-Dec-31-2020.xlsx'
df3 = pd.read_excel(excel_workbook, sheet_name = 'Raw Data Report')

new_df = pd.concat([df1,df2,df3])
new_df.to_csv("C:\\Users\\Gajraj Singh\\Downloads\\G-Device-Report-Mumzworld-Dec-1-2020-FEB-13-2020_New.csv", index = False)

In [19]:
# new_df = df.merge(df1, on='Ad ID')
# new_df = pd.merge(df,df1['Ad ID'],df['Ad ID'],df2['Ad ID'],on=['Ad ID'],how='left')
new_df = pd.concat([df, df2, df1])

In [20]:
new_df.head()

,Reporting Starts,Reporting Ends,Ad Name,Platform,Placement,Device Platform,Ad ID,Campaign Name,Ad Set Name,Ad Delivery,...,Checkouts Initiated,Mobile App Checkouts Initiated,Offline Checkouts Initiated,App Activations,Mobile App Sessions,Reach,Offline Adds to Cart,Age,Gender,Region
0,2020-11-02,2020-11-02,DC-RCB-Vr-Img,Messenger,Messenger Stories,Mobile App,23846068989190500,P-AI-Install_TopCities_All_Platforms_Cricket_V...,Install_TopCities_All_Platform_Vr_Interest_Foo...,inactive,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
1,2020-11-02,2020-11-02,EverydayValueOffer_InstallNow_Vr_Img,Messenger,Messenger Stories,Mobile App,23846002141610500,P-AI-Install_TopCities_Insta_Vr_Vidtech,Install_TopCities_Insta_Vr_Interest_Entertainm...,active,...,NaN,NaN,NaN,NaN,NaN,118,NaN,NaN,NaN,NaN
2,2020-11-02,2020-11-02,DC-RCB-Vr-Img,Instagram,Instagram Stories,Mobile App,23846068989190500,P-AI-Install_TopCities_All_Platforms_Cricket_V...,Install_TopCities_All_Platform_Vr_Interest_Foo...,inactive,...,NaN,NaN,NaN,2.0,2.0,3615,NaN,NaN,NaN,NaN
3,2020-11-02,2020-11-02,EverydayValueOffer_InstallNow_Vr_Img,Instagram,Instagram Stories,Mobile App,23846002141610500,P-AI-Install_TopCities_Insta_Vr_Vidtech,Install_TopCities_Insta_Vr_Interest_Entertainm...,active,...,NaN,NaN,NaN,31.0,31.0,5718,NaN,NaN,NaN,NaN
4,2020-11-02,2020-11-02,DC-RCB-Vr-Img,Facebook,Facebook Stories,Mobile App,23846068989190500,P-AI-Install_TopCities_All_Platforms_Cricket_V...,Install_TopCities_All_Platform_Vr_Interest_Foo...,inactive,...,NaN,NaN,NaN,3.0,3.0,181,NaN,NaN,NaN,NaN

In [21]:
new_df.to_csv('C:/Users/gajra/Desktop/Creative Dashboard/Daily/Daily-Raw.csv')

In [3]:
import os
import glob
import pandas as pd
os.chdir("C:\\Users\\gajra\\Downloads\\Boat_Device")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
df = pd.concat([pd.read_csv(f,encoding = "ISO-8859-1") for f in all_filenames ])
new_csv = df.fillna(0)
new_csv.rename(columns = {'Campaign Name':'Campaign_Name','Ad Set Name':'Ad_Set_Name','Ad ID':'Ad_ID',
                               'Call To Action':'Call_To_Action','Ad Set ID':'Ad_Set_ID','Campaign ID':'Campaign_ID'
                               ,'Ad Name':'Ad_Name','Delivery Status':'Delivery_Status','Delivery Level':'Delivery_Level'
                               ,'Result Type':'Result_Type','Amount Spent (INR)':'Amount_Spent_INR','Clicks (All)':'Clicks_All'
                               ,'Link Clicks':'Link_Clicks','App Installs':'App_Installs',
                               'Purchases Conversion Value':'Purchases_Conversion_Value',
                               'Landing Page Views':'Landing_Page_Views','Content Views':'Content_Views',
                               'Adds to Cart':'Adds_to_Cart','Adds to Cart Conversion Value':'Adds_to_Cart_Conversion_Value',
                               'Checkouts Initiated':'Checkouts_Initiated','Impression Device':'Impression_Device',
                               'Device Platform':'Device_Platform'}, inplace = True)
#export to csv
new_csv.to_csv( "New_Boat.csv", index=False,encoding = "ISO-8859-1")

In [54]:
new_csv.head()

,Campaign Name,Ad Set Name,Ad ID,Day,Age,Gender,Objective,Call To Action,Ad Set ID,Campaign ID,...,Adds to Cart,Adds to Cart Conversion Value,Checkouts Initiated,Dimension,Impression Device,Platform,Placement,Device Platform,call_to_action_type,Region
0,SB_Conversions_FocusProducts_Prospecting,Interest Based,6259957347013,2020-12-13,18-24,male,CONVERSIONS,SHOP_NOW,6258888976413,6258880964013,...,7,10269,10,Demo,NA,NA,NA,NA,NA,NA
1,SB_Conversions_FocusProducts_Prospecting,Lookalike - Airdopes,6259824331213,2020-12-13,45-54,male,CONVERSIONS,LEARN_MORE,6258880964813,6258880964013,...,NA,NA,NA,Demo,NA,NA,NA,NA,NA,NA
2,SB_Conversions_FocusProducts_Prospecting,Lookalike - Storm,6260008918813,2020-12-13,35-44,female,CONVERSIONS,SHOP_NOW,6260008050013,6258880964013,...,NA,NA,NA,Demo,NA,NA,NA,NA,NA,NA
3,SB_Conversions_FocusProducts_Prospecting,Lookalike - Storm,6260008918813,2020-12-13,35-44,unknown,CONVERSIONS,SHOP_NOW,6260008050013,6258880964013,...,NA,NA,NA,Demo,NA,NA,NA,NA,NA,NA
4,SB_Conversions_FocusProducts_Prospecting,Lookalike - Storm,6260008918813,2020-12-13,25-34,female,CONVERSIONS,SHOP_NOW,6260008050013,6258880964013,...,15,28385,10,Demo,NA,NA,NA,NA,NA,NA

## Merging multiple csv's using loop

In [52]:
import os
import glob
import pandas as pd
os.chdir("C:\\Users\\gajra\\Downloads\\Boat_Device")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f,encoding = "ISO-8859-1") for f in all_filenames ])
combined_csv['Dimension'] = 'Device'
combined_csv.rename(columns = {'Ã¯Â»Â¿"Campaign Name"':'Campaign Name'}, inplace = True)

#export to csv

combined_csv.to_csv( "combined_csv.csv", index=False,encoding = "ISO-8859-1")

C:\Users\gajra\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3263: DtypeWarning: Columns (4,5,7,31,32,33,34,36) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [ ]:
combined_csv.head()

## Static Merging

In [2]:
import pandas as pd
df1 = pd.read_csv("C:\\Users\\Gajraj Singh\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_os_2021-04-12T02_07_05.019-07_00.csv")
df2 = pd.read_csv("C:\\Users\\Gajraj Singh\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_country_2021-04-12T02_06_15.213-07_00.csv")
df3 = pd.read_csv("C:\\Users\\Gajraj Singh\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_lifestyle_category_2021-04-12T02_04_52.555-07_00.csv")
df4 = pd.read_csv("C:\\Users\\Gajraj Singh\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_gender_2021-04-12T02_04_24.186-07_00.csv")
df5 = pd.read_csv("C:\\Users\\Gajraj Singh\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_age_2021-04-12T02_04_12.574-07_00.csv")
df6 = pd.read_csv("C:\\Users\\Gajraj Singh\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_unknown_2021-04-12T02_03_07.253-07_00.csv")
# df5 = pd.read_csv("C:\\Users\\gajra\\Downloads\\738b627c-f8e6-418d-ab0c-bde717497399_age_2021-04-12T02_04_12.574-07_00.csv")

new_df = pd.concat([df1,df2,df3,df4,df5,df6])
# new_df.to_csv("C:\\Users\\Gajraj Singh\\Downloads\\G-Demo-Report-Mumzworld-Dec-1-2020-FEB-09-2020_New.csv", index = False)
# new_df = pd.concat([df2, df1])
# new_df['Dimension'] = 'Device'
# new_df1 = new_df.drop(['Starts', 'Ends','Reporting Ends','Reporting Starts'], axis = 1)

new_df.to_csv("C:\\Users\\Gajraj Singh\\Downloads\\FB\\new-Data.csv", index = False)

In [6]:
new_df.columns

Index(['Ad set name', 'Ad name', 'Campaign name', 'Campaign ID', 'Ad set ID',
       'Ad ID', 'Impression Device', 'Platform', 'Placement',
       'Device platform', 'Amount spent (INR)', 'Impressions', 'Reach',
       'Clicks (all)', 'Result Type', 'Results', 'Results [On ad]',
       'Results [1 Day After Viewing]', 'Results [28 Days After Clicking]',
       'Adds to cart', 'Adds to cart [1 Day After Viewing]',
       'Adds to cart [28 Days After Clicking]', 'App Installs',
       'App Installs [1 Day After Viewing]',
       'App Installs [28 Days After Clicking]', 'Purchases',
       'Purchases [1 Day After Viewing]', 'Purchases [28 Days After Clicking]',
       'Purchases Conversion Value',
       'Purchases Conversion Value [1 Day After Viewing]',
       'Purchases Conversion Value [28 Days After Clicking]', 'headline',
       'Body (ad settings)', 'call_to_action_type', 'Objective',
       'Reporting starts', 'Reporting ends', 'Region', 'Age', 'Gender'],
      dtype='object')

In [7]:
new_df1 = new_df.drop(['Results [On ad]','Results [1 Day After Viewing]','Results [28 Days After Clicking]',
                       'Adds to cart [1 Day After Viewing]','Adds to cart [28 Days After Clicking]',
                       'App Installs [1 Day After Viewing]','App Installs [28 Days After Clicking]',
                       'Purchases [1 Day After Viewing]', 'Purchases [28 Days After Clicking]',
                       'Purchases Conversion Value [1 Day After Viewing]','Purchases Conversion Value [28 Days After Clicking]',
                      'Reporting starts', 'Reporting ends'], axis = 1)

In [8]:
new_df1.to_csv("C:\\Users\\Gajraj Singh\\Downloads\\FB\\G-caratlane-Report.csv", index = False)

## Column Add, Rename, Drop

In [7]:
import pandas as pd
demo_df = pd.read_csv("C:\\Users\\gajra\\Downloads\\FB\\G-Demo-Report-Nov-Jan.csv")
# demo_df['Dimension'] = 'Device'
# demo_df1 = demo_df.drop(['Starts', 'Ends','Reporting Ends','Reporting Starts','Delivery Level','Delivery Status'], axis = 1)
demo_df1 = demo_df.drop(['Reporting Ends','Reporting Starts'], axis = 1)

demo_df1.to_csv("C:\\Users\\gajra\\Downloads\\FB\\G-Demo-Report-Nov-Jan_new.csv", index = False)

demo_df1.head()

,Campaign Name,Ad Set Name,Ad Name,Campaign ID,Ad Set ID,Ad ID,Day,Age,Gender,Objective,...,ThruPlays,Link Clicks,App Installs,Purchases,Purchases Conversion Value,Landing Page Views,Content Views,Adds to Cart,Adds to Cart Conversion Value,Checkouts Initiated
0,PR_NU_DPA_P$_LA3%ofHighValueCustomers_Nov'20,Top30SKUs_Price_UPNCR_Nov'20,Catalog_BillBuster_Nov'20,6226260836984,6226267180984,6226267180584,2020-12-15,35-44,male,PRODUCT_CATALOG_SALES,...,NaN,9.0,NaN,NaN,NaN,6.0,5.0,NaN,NaN,NaN
1,PR_DPA_Dynamic_P2_VC/ATC_NotPurchased_L14Days_...,Bhiwadi_VC/ATC_NotPurchased_RMKT,Catalog_BAU_Nov'20,6226305402784,6226308877984,6226308880984,2020-12-15,35-44,male,PRODUCT_CATALOG_SALES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PR_DPA_Dynamic_P0_VC/ATC_NotPurchased_L14Days_...,Bangalore_VC/ATC_NotPurchased_RMKT-V2,Catalog_BillBuster_Nov'20,6226290729384,6226307774184,6226409240384,2020-12-15,45-54,female,PRODUCT_CATALOG_SALES,...,NaN,17.0,NaN,2.0,2926.0,2.0,NaN,20.0,1906.0,NaN
3,PR_DPA_Dynamic_P0_VC/ATC_NotPurchased_L14Days_...,Bangalore_VC/ATC_NotPurchased_RMKT-V2,Catalog_BillBuster_Nov'20,6226290729384,6226307774184,6226409240384,2020-12-15,35-44,male,PRODUCT_CATALOG_SALES,...,NaN,44.0,1.0,6.0,11505.0,11.0,2.0,130.0,14627.0,6.0
4,PR_DPA_Dynamic_P0_VC/ATC_NotPurchased_L14Days_...,Bangalore_VC/ATC_NotPurchased_RMKT-V2,Catalog_BillBuster_Nov'20,6226290729384,6226307774184,6226409240384,2020-12-15,35-44,female,PRODUCT_CATALOG_SALES,...,NaN,116.0,NaN,8.0,13247.0,24.0,15.0,274.0,43611.0,8.0

## Splitting Pandas Dataframe by row index

In [59]:
new_csv.shape

(153148, 37)

In [68]:
new_csv_1 = new_csv.iloc[:30629,:]
new_csv_2 = new_csv.iloc[30630:61259,:]
new_csv_3 = new_csv.iloc[61260:91889,:]
new_csv_4 = new_csv.iloc[91890:122519,:]
new_csv_5 = new_csv.iloc[122520:,:] 

new_csv_1.to_csv("C:\\Users\\gajra\\Downloads\\Boat_Device\\Boat1.csv", index = False)
new_csv_2.to_csv("C:\\Users\\gajra\\Downloads\\Boat_Device\\Boat2.csv", index = False)
new_csv_3.to_csv("C:\\Users\\gajra\\Downloads\\Boat_Device\\Boat3.csv", index = False)
new_csv_4.to_csv("C:\\Users\\gajra\\Downloads\\Boat_Device\\Boat4.csv", index = False)
new_csv_5.to_csv("C:\\Users\\gajra\\Downloads\\Boat_Device\\Boat5.csv", index = False)

In [67]:
new_csv.iloc[1:3, 0:3]

,Campaign Name,Ad Set Name,Ad ID
1,SB_Conversions_FocusProducts_Prospecting,Lookalike - Airdopes,6259824331213
2,SB_Conversions_FocusProducts_Prospecting,Lookalike - Storm,6260008918813