In [81]:
import os
import glob
import pandas as pd
import re
os.chdir('C:/Users/Gajraj Singh/Downloads')
extension = 'csv'

dfs = []
for i in glob.glob('*byDate_tyroo_*.{}'.format(extension)):
    j = re.findall("byDate_tyroo_(\w+)_2021", i)
    df = pd.read_csv(i,encoding = "ISO-8859-1")
    df['Account_Name'] = j[0]
    df.rename(columns = {df.columns[0]: 'id',}, inplace = True)
    df = df[df.id != 'total']
    df = df.iloc[: , 1:]
    df = df.fillna(0)
    dfs.append(df)
new_df = pd.concat(dfs, axis=0, ignore_index=True)
new_df = new_df[['Account_Name','From Date','To Date','Amount Spent','Impressions','Clicks','Conversions (click)'
                 ,'Conversions Value (click)','FirstDeposit Conversions (click)','FirstDeposit Conversions value (click)',
                 'OrderPlaced Conversions (click)','Addtocart Conversions (click)']]
new_df = new_df.fillna(0)
new_df.head()

,Account_Name,From Date,To Date,Amount Spent,Impressions,Clicks,Conversions (click),Conversions Value (click),FirstDeposit Conversions (click),FirstDeposit Conversions value (click),OrderPlaced Conversions (click),Addtocart Conversions (click)
0,mahindra_mf_,2021-08-02,2021-08-02,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,mahindra_mf_,2021-08-01,2021-08-01,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21kschools_d,2021-08-02,2021-08-02,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21kschools_d,2021-08-01,2021-08-01,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,360_realtors,2021-08-02,2021-08-02,413.27,113109.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
new_df.to_csv('C:/Users/Gajraj Singh/Downloads/new_df.csv', index=False,encoding = "ISO-8859-1")

In [10]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select

# chrome_path = 
# driver = webdriver.Chrome(executable_path=r)
driver = webdriver.Chrome(executable_path=r'C:/chromedriver/chromedriver.exe')

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--disable-popup-blocking")

driver.maximize_window()
driver.get("https://www.indiapost.gov.in/VAS/Pages/findpincode.aspx")

# time.sleep(3)

element = driver.find_element_by_id("ctl00_SPWebPartManager1_g_28a6af46_5d77_4b7e_aaa2_68d16bfca954_ctl00_drpStates")
drp = Select(element)
drp.select_by_value("10")
element2 = driver.find_element_by_id("ctl00_SPWebPartManager1_g_28a6af46_5d77_4b7e_aaa2_68d16bfca954_ctl00_drpDistricts")
drp = Select(element2)
drp.select_by_visible_text("Bidar")
# username.clear()
# username.send_keys("harshit.v@tyroo.com")

# password = driver.find_element_by_id("signin-member-password")
# password.clear()
# password.send_keys("Tyr00@1234")

# driver.find_element_by_id("loginButton").click()